<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class cadastroAuxiliar extends Model
{
    protected $fillable = ['id_usuario','tipo_manual'];
    protected $guarded = ['id','created_at', 'updated_at'];
    protected $table = 'cadastro_auxiliar_tipo_manual';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model){
            $model->id_usuario=1;
        });

        static::updating(function($model){
            $model->id_usuario=1;
        });
    }

   
}
