<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\cadastroAuxiliar;

class CadastroManual extends Model
{
    protected $fillable = ['descricao', 'tipo_manual','arquivo_pdf', 'id_usuario'];
    protected $guarded = ['id', 'updated_at', 'created_at'];
    protected $dates = ['updated_at', 'created_at'];
    protected $table = 'cadastro_manual';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model){
            $model->id_usuario=1;
        });

        static::updating(function($model){
            $model->id_usuario=1;
        });
    }

    public function tipoManual(){
        return $this->hasOne(cadastroAuxiliar::class,'id', 'tipo_manual');
    }

    
}
